# Generated by Django 5.2.6 on 2025-11-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='purchased_items',
            field=models.ManyToManyField(blank=True, help_text='Items the user has bought', to='shop.shopitem'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tokens',
            field=models.IntegerField(default=0, help_text='Spendable currency'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
