# Generated by Django 5.2.6 on 2025-09-07 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='lost_items/')),
                ('last_known_location', models.CharField(blank=True, max_length=200)),
                ('contact_info', models.CharField(help_text='Enter your phone number or email.', max_length=200)),
                ('status', models.CharField(choices=[('Lost', 'Lost'), ('Found', 'Found')], default='Lost', max_length=10)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-reported_at'],
            },
        ),
    ]
