# Generated by Django 5.2.6 on 2025-09-09 15:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_reply'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='downvotes',
            field=models.ManyToManyField(blank=True, related_name='reply_downvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reply',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='reply_upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
