# Generated by Django 5.2.6 on 2025-09-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_reply_downvotes_reply_upvotes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doubt',
            name='video_url',
        ),
        migrations.AddField(
            model_name='doubt',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='doubt_images/'),
        ),
    ]
