# Generated by Django 5.2.6 on 2025-09-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
