# Generated by Django 5.2.6 on 2025-09-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meme',
            old_name='reel_link',
            new_name='embed_link',
        ),
        migrations.AddField(
            model_name='meme',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meme',
            name='video_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meme',
            name='meme_type',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], max_length=5),
        ),
    ]
