# Generated by Django 5.2.6 on 2025-09-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0003_meme_likes_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meme',
            name='embed_link',
        ),
        migrations.RemoveField(
            model_name='meme',
            name='thumbnail_url',
        ),
        migrations.AlterField(
            model_name='meme',
            name='meme_type',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video Link')], max_length=5),
        ),
    ]
